---
- name: Update multiple sysctl parameters
  hosts: servers
  tasks:
    - name: Set sysctl parameters
      lineinfile:
        path: /etc/sysctl.conf
        regexp: "^{{ item.key }}\\s*="
        line: "{{ item.key }} = {{ item.value }}"
        state: present
        create: yes
      loop:
        - { key: "net.ipv4.ip_forward", value: "1" }
        - { key: "vm.swappiness", value: "10" }
        - { key: "fs.file-max", value: "2097152" }

    - name: Apply sysctl changes
      command: sysctl -p
