---
- name: Update all hosts with the latest packages
  hosts: all
  become: yes
  tasks:
    - name: Update all packages on Red Hat-based systems
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
