---
- name: Create test user
  become: true
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: /bin/bash
    groups: wheel

- name: Set authorized key for test user (secure)
  become: true
  ansible.posix.authorized_key:
    user: "{{ user_name }}"
    key: "{{ user_pubkey }}"
    state: present
  vars_files:
    - ../secrets/vault.yml

- name: Sudoers entry for test user
  become: true
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ user_name }}"
    content: "{{ user_name }} ALL=(ALL) NOPASSWD:ALL"
    mode: '0440'