---
- name: Create logical volume for WebApp
  become: true
  community.general.lvol:
    vg: rhel
    lv: web
    size: "{{ web_fs_size }}"
    state: present

- name: Format WebApp volume
  become: true
  ansible.builtin.filesystem:
    fstype: xfs
    dev: "/dev/rhel/web"

- name: Mount /opt/web
  become: true
  ansible.builtin.mount:
    path: /opt/web
    src: "/dev/rhel/web"
    fstype: xfs
    state: mounted

- name: Create webid user
  become: true
  ansible.builtin.user:
    name: "{{ web_user }}"
    shell: /bin/bash

- name: Deploy webapp with Jinja2 template
  become: true
  ansible.builtin.template:
    src: webapp.j2
    dest: /opt/web/index.html
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    mode: '0644'
  vars:
    mongo_host: "localhost"
    mongo_port: 27017

- name: Start simple web server
  become: true
  ansible.builtin.shell: |
    nohup python3 -m http.server 8080 --directory /opt/web &
  args:
    creates: /tmp/webserver.pid

- name: Provide external webapp link
  ansible.builtin.debug:
    msg: "WebApp is running at http://{{ ansible_default_ipv4.address }}:8080/"