vm_name: "vm02"
vm_disk_gb: 20
vm_disk_datastore: "ds2"
vm_hw_ram_mb: 2048
vm_hw_cpu_n: 1

vm_disks:
  - size_gb: 20
    type: thin
    datastore: ds2
  - size_gb: 5
    type: thin
    datastore: ds2

vm_networks:
  - name: "VM Network"
    start_connected: yes
    device_type: vmxnet3
    type: static
    ip: "192.168.0.172"
    netmask: "255.255.255.0"
    gateway: "192.168.0.1"
    dns_servers:
      - "192.168.0.101"
  - name: "VM Network"
    start_connected: yes
    device_type: vmxnet3
    type: dhcp
